"""Shared ReportLab PDF template helpers for NyayaSetu documents."""

from __future__ import annotations

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, Spacer


def get_pdf_styles():
    """Return shared style sheet for legal documents."""
    styles = getSampleStyleSheet()
    styles.add(
        ParagraphStyle(
            name="NyHeader",
            parent=styles["Heading1"],
            fontName="Helvetica-Bold",
            fontSize=16,
            leading=20,
            alignment=1,
            textColor=colors.HexColor("#1E2D4D"),
            spaceAfter=8,
        )
    )
    styles.add(
        ParagraphStyle(
            name="NySubHeader",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=10,
            leading=13,
            alignment=1,
            textColor=colors.HexColor("#4B5563"),
            spaceAfter=10,
        )
    )
    styles.add(
        ParagraphStyle(
            name="NyClause",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=10.5,
            leading=14,
            spaceAfter=6,
        )
    )
    styles.add(
        ParagraphStyle(
            name="NyStrong",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=10.5,
            leading=14,
            textColor=colors.HexColor("#111827"),
        )
    )
    return styles


def build_header(story: list, title: str, subtitle: str = "") -> None:
    """Add shared header block to story."""
    styles = get_pdf_styles()
    story.append(Paragraph("⚖️ NyayaSetu", styles["NySubHeader"]))
    story.append(Paragraph(title, styles["NyHeader"]))
    if subtitle:
        story.append(Paragraph(subtitle, styles["NySubHeader"]))
    story.append(Spacer(1, 0.12 * inch))


def draw_page_chrome(canvas, doc, watermark: str = "COMPUTER GENERATED") -> None:
    """Draw watermark, page number, and footer."""
    canvas.saveState()
    canvas.setFillColor(colors.Color(0.86, 0.86, 0.86, alpha=0.35))
    canvas.setFont("Helvetica-Bold", 40)
    canvas.translate(A4[0] / 2, A4[1] / 2)
    canvas.rotate(45)
    canvas.drawCentredString(0, 0, watermark)
    canvas.restoreState()

    canvas.saveState()
    canvas.setFont("Helvetica", 8.5)
    canvas.setFillColor(colors.HexColor("#6B7280"))
    canvas.drawCentredString(A4[0] / 2, 0.55 * inch, f"Page {doc.page}")
    canvas.drawCentredString(A4[0] / 2, 0.35 * inch, "Generated by NyayaSetu ODR Platform | Not legal advice")
    canvas.restoreState()

